title = "Riley Schuit"
baseURL = "https://resume.rileyschuit.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Rathdrum, ID"
email = "riley.schuit@gmail.com"
favicon = "/favicon.ico"
firstName = "Riley"
lastName = "Schuit"
phone = "1-208-667-0140"
profileImage = "img/workpic.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true

[params.google]

# [params.google.analytics]
# trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/rileyschuit/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/rileyschuit/"
name = "GitHub"

[[params.handles]]
link = "https://hub.docker.com/u/rileyschuit"
name = "Docker"

# [[params.handles]]
# link = "https://stackoverflow.com/users/story/82880"
# name = "Stack Overflow"

# [[params.handles]]
# link = "https://keybase.io/edwardawebb"
# name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
